apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  type: NodePort
  ports: 
    - name: admin-port
      port: 8086
      targetPort: 8086
      nodePort: 30086

---
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: admin-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8086