apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: admin-server
data:
  username: YWRtaW4=
  password: czNjcjN0

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-server
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    server:
      port: 8086
    spring:
      cloud:
        kubernetes:
          catalog-services-watch:
            catalogServicesWatchDelay: 5000
            enabled: true
          discovery:
            all-namespaces: true
            service-labels:
              spring-boot-admin: "true"
      security:
        user:
          name: ${ADMIN_USER}
          password: ${ADMIN_PASSWD}

---
          
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  type: NodePort
  ports: 
    - name: admin-port
      port: 8086
      targetPort: 8086
      nodePort: 30086

---
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
        metrics: "on"        
    spec:
      containers:
      - name: admin-server
        image: admin-server
        imagePullPolicy: Never
        env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: admin-server
                key: username
          - name: ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                name: admin-server
                key: password        
        ports:
        - containerPort: 8086