apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    server:
      port: 8090
    spring:
      zipkin:
        baseUrl: http://zipkin:9411
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: serie-service
              uri: lb://serie-service
              predicates:
                - Path=/serie/**
            - id: film-service
              uri: lb://film-service
              predicates:
                - Path=/film/**
        kubernetes:
          reload:
            enabled: true
            strategy: shutdown