apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    type: actuator  
spec:
  selector:
    app: gateway-server
  type: NodePort
  ports: 
    - name: gateway-port
      port: 8090
      targetPort: 8090
      nodePort: 30090

---
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: gateway-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8090