apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    server:
      port: 8090
    spring:
      zipkin:
        baseUrl: http://zipkin.zipkin:9411
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: serie-service
              uri: lb://serie-service
              predicates:
                - Path=/serie/**
            - id: film-service
              uri: lb://film-service
              predicates:
                - Path=/film/**
        kubernetes:
          reload:
            enabled: true
            strategy: shutdown

---
            
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    spring-boot-admin: "true"
spec:
  selector:
    app: gateway-server
  type: NodePort
  ports: 
    - name: gateway-port
      port: 8090
      targetPort: 8090
      nodePort: 30090

---
      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
        metrics: "on"        
    spec:
      containers:
      - name: gateway-server
        image: gateway-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8090