## Prometheus server ConfigMap entries
serverFiles:

  prometheus.yml:
    rule_files:
      - /etc/config/rules
      - /etc/config/alerts

    scrape_configs:
      - job_name: 'spring-actuator'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_metrics]
            regex: on
            action: keep
        metrics_path: '/actuator/prometheus'
        basic_auth:
          username: 'admin'
          password: 's3cr3t'
