kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
    apiGroup: ""
  - kind: ServiceAccount
    name: default
    namespace: monitoring
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: api-reader
  apiGroup: ""
