kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: api-reader
  apiGroup: ""
