apiVersion: v1
kind: ConfigMap
metadata:
  name: serie-service
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    server:
      port: ${PORT:0}
    spring:
      zipkin:
        baseUrl: http://zipkin.zipkin:9411

---

apiVersion: v1
kind: Service
metadata:
  name: serie-service
  labels:
    spring-boot-admin: "true"
spec:
  selector:
    app: serie-service
  ports: 
    - name: serie-port
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: serie-service
  labels:
    app: serie-service
spec:
  selector:
    matchLabels:
      app: serie-service
  template:
    metadata:
      labels:
        app: serie-service
        metrics: "on"        
    spec:
      containers:
      - name: serie-service
        image: serie-service
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "8080"
        ports:
        - name: serie-port
          containerPort: 8080      