apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  type: NodePort
  ports: 
    - name: config-port
      port: 8081
      targetPort: 8081
      nodePort: 30081