apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    type: actuator
spec:
  selector:
    app: user-service
  # ports: 
  #   - name: user-port
  #     port: 8080
  type: NodePort
  ports: 
    - name: user-port
      port: 8080
      targetPort: 8080
      nodePort: 30080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "8080"
        ports:
        - name: user-port
          containerPort: 8080        