apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    spring-boot-admin: "true"
spec:
  selector:
    app: zipkin
  type: NodePort
  ports: 
    - name: default-port
      port: 9411
      targetPort: 9411
      nodePort: 30411

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: zipkin
  labels:
    app: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - name: default-port
          containerPort: 9411