server:
  port: 8081

spring:
  application:
    name: config-server
  security:
    user:
      name: config
      password: s3cr3t
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidmoros/poc
          search-paths: /microservices/config-data

management:
  endpoints:
    web:
      exposure:
        include: "*"