spring:
  zipkin:
    baseUrl: http://zipkin:9411

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"